description: Unser familiäres Kiez-Saunabad befindet sich in Prenzlauer Berg. In der Blockbohlensauna erwarten Sie Aroma-Aufgüsse mit Blick in unseren Sauna-Garten.
url: https://www.saunabad-berlin.de

og:
  title: Saunabad Berlin - Sauna und Wellness in Prenzlauer Berg
  description: Unser familiäres Kiez-Saunabad befindet sich in Prenzlauer Berg. In der Blockbohlensauna erwarten Sie Aroma-Aufgüsse mit Blick in unseren Sauna-Garten.
  url: https://www.saunabad-berlin.de
  type: website
  image: /images/rykestraße.jpg
  locale: de_DE
